In [1]:
import os
import pandas as pd
import numpy as np

In [2]:
#os.chdir('Dataset')

In [3]:
testData=pd.read_csv("C:\\Users\\Rebecca\\Documents\\TL Study Docs\\ML\\Dataset\\adult.csv",na_values=['#NAME?'])
testData

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39.0,State-gov,77516.0,Bachelors,13.0,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50.0,Self-emp-not-inc,83311.0,Bachelors,13.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38.0,Private,215646.0,HS-grad,9.0,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53.0,Private,234721.0,11th,7.0,Married-civ-spouse,Handlers-cleaners,Husband,Black,NaN,0,0,40,United-States,<=50K
4,28.0,Private,338409.0,Bachelors,13.0,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
5,37.0,Private,284582.0,Masters,14.0,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
6,49.0,Private,160187.0,9th,5.0,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0,0,16,Jamaica,<=50K
7,52.0,Self-emp-not-inc,209642.0,HS-grad,9.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
8,31.0,Private,45781.0,Masters,14.0,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K
9,42.0,Private,159449.0,Bachelors,13.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178,0,40,United-States,>50K
10,37.0,Private,280464.0,Some-college,10.0,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0,0,80,United-States,>50K
11,30.0,State-gov,141297.0,Bachelors,13.0,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0,0,40,India,>50K
12,23.0,Private,122272.0,Bachelors,13.0,Never-married,Adm-clerical,Own-child,White,Female,0,0,30,United-States,<=50K
13,32.0,Private,205019.0,Assoc-acdm,12.0,Never-married,Sales,Not-in-family,Black,Male,0,0,50,United-States,<=50K
14,40.0,Private,121772.0,Assoc-voc,11.0,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,0,0,40,?,>50K
15,34.0,Private,245487.0,7th-8th,4.0,Married-civ-spouse,Transport-moving,Husband,Amer-Indian-Eskimo,Male,0,0,45,Mexico,<=50K
16,NaN,Self-emp-not-inc,NaN,HS-grad,9.0,Never-married,Farming-fishing,Own-child,White,Male,0,0,35,United-States,<=50K
17,32.0,Private,186824.0,HS-grad,9.0,Never-married,Machine-op-inspct,Unmarried,White,Male,0,0,40,United-States,<=50K
18,38.0,Private,28887.0,11th,7.0,Married-civ-spouse,Sales,Husband,White,Male,0,0,50,United-States,<=50K
19,43.0,Self-emp-not-inc,292175.0,Masters,14.0,Divorced,Exec-managerial,Unmarried,White,Female,0,0,45,United-States,>50K
20,NaN,Private,193524.0,Doctorate,16.0,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K
21,54.0,Private,302146.0,HS-grad,9.0,Separated,Other-service,Unmarried,Black,Female,0,0,20,United-States,<=50K
22,35.0,Federal-gov,76845.0,9th,5.0,Married-civ-spouse,Farming-fishing,Husband,Black,Male,0,0,40,United-States,<=50K
23,43.0,Private,117037.0,11th,7.0,Married-civ-spouse,Transport-moving,Husband,White,Male,0,2042,40,United-States,<=50K
24,59.0,Private,109015.0,HS-grad,9.0,Divorced,Tech-support,Unmarried,White,Female,0,0,40,United-States,<=50K
25,56.0,Local-gov,216851.0,Bachelors,13.0,Married-civ-spouse,Tech-support,Husband,White,Male,0,0,40,United-States,>50K
26,19.0,Private,168294.0,HS-grad,9.0,Never-married,Craft-repair,Own-child,White,Male,0,0,40,United-States,<=50K
27,54.0,?,180211.0,Some-college,10.0,Married-civ-spouse,?,Husband,Asian-Pac-Islander,Male,0,0,60,South,>50K
28,39.0,Private,367260.0,?,NaN,Divorced,Exec-managerial,Not-in-family,White,Male,0,0,80,United-States,<=50K
29,49.0,Private,193366.0,HS-grad,9.0,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4970,51.0,?,203953.0,HS-grad,9.0,Married-civ-spouse,?,Husband,White,Male,0,0,40,United-States,>50K
4971,46.0,State-gov,29696.0,HS-grad,9.0,Married-civ-spouse,Transport-moving,Husband,White,Male,0,0,40,United-States,<=50K
4972,30.0,Private,315640.0,Doctorate,16.0,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0,1977,40,China,>50K
4973,37.0,Private,632613.0,10th,6.0,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,35,Mexico,<=50K
4974,56.0,Private,282023.0,Prof-school,15.0,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,45,United-States,>50K
4975,29.0,Private,77760.0,HS-grad,9.0,Married-civ-spouse,Adm-clerical,Husband,White,Male,0,0,45,United-States,<=50K
4976,46.0,Self-emp-not-inc,148599.0,Masters,14.0,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,50,United-States,>50K
4977,55.0,Private,414994.0,HS-grad,9.0,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
4978,45.0,Private,339863.0,Bachelors,13.0,Divorced,Sales,Not-in-family,White,Male,8614,0,48,United-States,>50K
4979,34.0,Private,499249.0,HS-grad,9.0,Married-spouse-absent,Handlers-cleaners,Not-in-family,White,Male,0,0,40,Guatemala,<=50K
4980,45.0,?,144354.0,9th,5.0,Separated,?,Own-child,Black,Male,0,0,40,United-States,<=50K
4981,41.0,Private,252058.0,Bachelors,13.0,Never-married,Adm-clerical,Not-in-family,White,Male,0,0,40,United-States,<=50K
4982,22.0,?,99543.0,Some-college,10.0,Never-married,?,Own-child,NaN,Male,0,0,20,United-States,<=50K
4983,34.0,Private,117963.0,Prof-school,15.0,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,50,United-States,>50K
4984,27.0,Private,194652.0,HS-grad,9.0,Never-married,Craft-repair,Own-child,Black,Male,0,0,40,United-States,<=50K
4985,29.0,Private,299705.0,Some-college,10.0,Never-married,Handlers-cleaners,Unmarried,Black,Male,0,0,37,United-States,<=50K
4986,19.0,Federal-gov,27433.0,12th,8.0,Never-married,Other-service,Own-child,White,Female,0,0,30,United-States,<=50K
4987,47.0,Local-gov,39986.0,Bachelors,13.0,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,40,United-States,<=50K
4988,43.0,Self-emp-inc,135342.0,Some-college,10.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,50,United-States,>50K
4989,52.0,Private,270142.0,Assoc-voc,11.0,Separated,Exec-managerial,Unmarried,Black,Female,0,0,60,United-States,<=50K
4990,33.0,Self-emp-not-inc,118267.0,Assoc-acdm,12.0,Divorced,Sales,Not-in-family,White,Male,0,0,60,United-States,<=50K
4991,29.0,Private,266043.0,9th,5.0,Married-civ-spouse,Transport-moving,Husband,White,Male,0,0,40,United-States,<=50K
4992,23.0,Private,35633.0,HS-grad,9.0,Married-civ-spouse,Handlers-cleaners,Husband,White,Male,0,0,40,United-States,<=50K
4993,23.0,Private,74568.0,Some-college,10.0,Never-married,Exec-managerial,Not-in-family,White,Male,0,0,40,United-States,<=50K
4994,39.0,Private,214816.0,Bachelors,13.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,60,United-States,<=50K
4995,43.0,Private,222971.0,5th-6th,3.0,Never-married,Machine-op-inspct,Unmarried,White,Female,0,0,40,Mexico,<=50K
4996,31.0,Private,259425.0,HS-grad,9.0,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,>50K
4997,47.0,Self-emp-inc,212120.0,HS-grad,9.0,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,>50K
4998,NaN,Private,245880.0,HS-grad,9.0,Never-married,Adm-clerical,Not-in-family,White,Male,0,0,60,United-States,<=50K
4999,58.0,Local-gov,54947.0,Some-college,10.0,Never-married,Prof-specialty,Not-in-family,White,Female,0,0,55,United-States,<=50K

In [4]:
testDF=pd.DataFrame(testData)
testDF.describe()

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week
count,4952.000000,4.893000e+03,4943.000000,5000.000000,5000.000000,5000.000000
mean,38.586430,1.909752e+05,10.080316,1033.640200,93.696800,40.519000
std,13.582256,1.065747e+05,2.535268,7051.802077,410.801418,12.109193
min,17.000000,1.930200e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.177470e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.795330e+05,10.000000,0.000000,0.000000,40.000000
75%,47.000000,2.418950e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.033222e+06,16.000000,99999.000000,2547.000000,99.000000

In [5]:
os.getcwd()

'C:\\Users\\Rebecca\\Documents\\TL Study Docs\\Python Scripts'

In [6]:
testDF.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education_num',
       'marital_status', 'occupation', 'relationship', 'race', 'sex',
       'capital_gain', 'capital_loss', 'hours_per_week', 'native_country',
       'income'],
      dtype='object')

In [7]:
print(testDF['income'].value_counts())

<=50K    3779
>50K     1221
Name: income, dtype: int64

In [8]:
testDF['income']=[0 if x=='<=50K' else 1 for x in testDF['income']]
testDF[:3]

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39.0,State-gov,77516.0,Bachelors,13.0,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,0
1,50.0,Self-emp-not-inc,83311.0,Bachelors,13.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,0
2,38.0,Private,215646.0,HS-grad,9.0,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,0

###### Assign X data frame with values from all columns except Income column------Assign Y data frame with values from the column Income

In [9]:
x=testDF.drop('income',1)
y=testDF['income']

In [10]:
x[:3]

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country
0,39.0,State-gov,77516.0,Bachelors,13.0,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States
1,50.0,Self-emp-not-inc,83311.0,Bachelors,13.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States
2,38.0,Private,215646.0,HS-grad,9.0,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States

In [11]:
y[:3]

0    0
1    0
2    0
Name: income, dtype: int64

In [12]:
x['education'].head(5)

0    Bachelors
1    Bachelors
2      HS-grad
3         11th
4    Bachelors
Name: education, dtype: object

In [13]:
x['education'].nunique()

17

In [14]:
x['education'].unique()

array(['Bachelors', 'HS-grad', '11th', 'Masters', '9th', 'Some-college',
       'Assoc-acdm', 'Assoc-voc', '7th-8th', 'Doctorate', '?',
       'Prof-school', '5th-6th', '10th', '1st-4th', 'Preschool', '12th'],
      dtype=object)

In [15]:
pd.get_dummies(x['education']).head(5)

,10th,11th,12th,1st-4th,5th-6th,7th-8th,9th,?,Assoc-acdm,Assoc-voc,Bachelors,Doctorate,HS-grad,Masters,Preschool,Prof-school,Some-college
0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
3,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0

In [16]:
x['workclass'].value_counts()

Private             3435
Self-emp-not-inc     383
?                    331
Local-gov            329
State-gov            193
Self-emp-inc         182
Federal-gov          146
Without-pay            1
Name: workclass, dtype: int64

In [17]:
x.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education_num',
       'marital_status', 'occupation', 'relationship', 'race', 'sex',
       'capital_gain', 'capital_loss', 'hours_per_week', 'native_country'],
      dtype='object')

In [18]:
x.dtypes

age               float64
workclass          object
fnlwgt            float64
education          object
education_num     float64
marital_status     object
occupation         object
relationship       object
race               object
sex                object
capital_gain        int64
capital_loss        int64
hours_per_week      int64
native_country     object
dtype: object

In [19]:
for col_name in x.columns:
    if x[col_name].dtypes=='object':
        lengthColumn=len(x[col_name].unique())
        print("Features '{col_name}' has '{lengthColumn}' unique categories.".format(col_name=col_name,lengthColumn=lengthColumn))

Features 'workclass' has '8' unique categories.
Features 'education' has '17' unique categories.
Features 'marital_status' has '7' unique categories.
Features 'occupation' has '15' unique categories.
Features 'relationship' has '6' unique categories.
Features 'race' has '6' unique categories.
Features 'sex' has '3' unique categories.
Features 'native_country' has '40' unique categories.

In [20]:
x['sex'].unique()

array(['Male', nan, 'Female'], dtype=object)

In [21]:
for col_name in x.columns:
    if 
    'object':
        unique_cat=x[col_name].nunique()
        print("")

In [22]:
x['native_country'].value_counts().sort_values(ascending=False).head(10)

United-States    4465
Mexico            104
?                  97
Canada             28
Philippines        22
Germany            22
Puerto-Rico        16
England            16
El-Salvador        16
Jamaica            15
Name: native_country, dtype: int64

In [23]:
x['native_country']=['United-States' if x=='United-States' else 'Other' for x in x['native_country']]
print(x['native_country'].value_counts().sort_values(ascending=False))

United-States    4465
Other             535
Name: native_country, dtype: int64

In [24]:
to_dummylist=['education','workclass','marital_status','occupation','relationship','race','sex','native_country']

In [25]:
def dummy_list(df,to_dummylist):
    for dummy in to_dummylist:
        dummies=pd.get_dummies(df[dummy],prefix='dummy',dummy_na=False)
        df=df.drop(dummy,1)
        df=pd.concat([df,dummies],axis=1)
    return df

In [29]:
x=dummy_list(x,to_dummylist)

In [30]:
x.dtypes

age                         float64
fnlwgt                      float64
education_num               float64
capital_gain                  int64
capital_loss                  int64
hours_per_week                int64
dummy_10th                    uint8
dummy_11th                    uint8
dummy_12th                    uint8
dummy_1st-4th                 uint8
dummy_5th-6th                 uint8
dummy_7th-8th                 uint8
dummy_9th                     uint8
dummy_?                       uint8
dummy_Assoc-acdm              uint8
dummy_Assoc-voc               uint8
dummy_Bachelors               uint8
dummy_Doctorate               uint8
dummy_HS-grad                 uint8
dummy_Masters                 uint8
dummy_Preschool               uint8
dummy_Prof-school             uint8
dummy_Some-college            uint8
dummy_?                       uint8
dummy_Federal-gov             uint8
dummy_Local-gov               uint8
dummy_Private                 uint8
dummy_Self-emp-inc            uint8
dummy_Self-emp-not-inc        uint8
dummy_State-gov               uint8
                             ...
dummy_?                       uint8
dummy_Adm-clerical            uint8
dummy_Armed-Forces            uint8
dummy_Craft-repair            uint8
dummy_Exec-managerial         uint8
dummy_Farming-fishing         uint8
dummy_Handlers-cleaners       uint8
dummy_Machine-op-inspct       uint8
dummy_Other-service           uint8
dummy_Priv-house-serv         uint8
dummy_Prof-specialty          uint8
dummy_Protective-serv         uint8
dummy_Sales                   uint8
dummy_Tech-support            uint8
dummy_Transport-moving        uint8
dummy_Husband                 uint8
dummy_Not-in-family           uint8
dummy_Other-relative          uint8
dummy_Own-child               uint8
dummy_Unmarried               uint8
dummy_Wife                    uint8
dummy_Amer-Indian-Eskimo      uint8
dummy_Asian-Pac-Islander      uint8
dummy_Black                   uint8
dummy_Other                   uint8
dummy_White                   uint8
dummy_Female                  uint8
dummy_Male                    uint8
dummy_Other                   uint8
dummy_United-States           uint8
Length: 68, dtype: object

In [47]:
x.isnull().sum().sort_values(ascending=False).head()

fnlwgt             107
education_num       57
age                 48
dummy_Local-gov      0
dummy_Masters        0
dtype: int64

In [46]:
x[:2]

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week,dummy_10th,dummy_11th,dummy_12th,dummy_1st-4th,...,dummy_Wife,dummy_Amer-Indian-Eskimo,dummy_Asian-Pac-Islander,dummy_Black,dummy_Other,dummy_White,dummy_Female,dummy_Male,dummy_Other,dummy_United-States
0,39.0,77516.0,13.0,2174,0,40,0,0,0,0,...,0,0,0,0,0,1,0,1,0,1
1,50.0,83311.0,13.0,0,0,13,0,0,0,0,...,0,0,0,0,0,1,0,1,0,1

In [53]:
xx=x
xxx=x
from sklearn.preprocessing import Imputer
imp=Imputer(missing_values='NaN',strategy='median',axis=0)
imp.fit(xx)
xx=pd.DataFrame(data=imp.transform(xx),columns=xx.columns)
xx.isnull().sum().sort_values(ascending=False).head()

dummy_United-States    0
dummy_Federal-gov      0
dummy_HS-grad          0
dummy_Masters          0
dummy_Preschool        0
dtype: int64

In [55]:
xxx=pd.DataFrame(data=imp.fit_transform(xxx),columns=xxx.columns)

###### AUTO.csv

In [56]:
auto=pd.read_csv("C:\\Users\\Rebecca\\Documents\\TL Study Docs\\ML\\Dataset\\auto.csv",index_col=0)
auto

,symboling,normalized_losses,make,fuel_type,aspiration,num_doors,body_style,drive_wheels,engine_location,wheel_base,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.00,111.0,5000.0,21,27,13495.0
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.00,111.0,5000.0,21,27,16500.0
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.00,154.0,5000.0,19,26,16500.0
3,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.00,102.0,5500.0,24,30,13950.0
4,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.00,115.0,5500.0,18,22,17450.0
5,2,NaN,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.50,110.0,5500.0,19,25,15250.0
6,1,158.0,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.50,110.0,5500.0,19,25,17710.0
7,1,NaN,audi,gas,std,four,wagon,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.50,110.0,5500.0,19,25,18920.0
8,1,158.0,audi,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.40,8.30,140.0,5500.0,17,20,23875.0
9,0,NaN,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.40,7.00,160.0,5500.0,16,22,NaN
10,2,192.0,bmw,gas,std,two,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.80,101.0,5800.0,23,29,16430.0
11,0,192.0,bmw,gas,std,four,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.80,101.0,5800.0,23,29,16925.0
12,0,188.0,bmw,gas,std,two,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.00,121.0,4250.0,21,28,20970.0
13,0,188.0,bmw,gas,std,four,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.00,121.0,4250.0,21,28,21105.0
14,1,NaN,bmw,gas,std,four,sedan,rwd,front,103.5,...,164,mpfi,3.31,3.19,9.00,121.0,4250.0,20,25,24565.0
15,0,NaN,bmw,gas,std,four,sedan,rwd,front,103.5,...,209,mpfi,3.62,3.39,8.00,182.0,5400.0,16,22,30760.0
16,0,NaN,bmw,gas,std,two,sedan,rwd,front,103.5,...,209,mpfi,3.62,3.39,8.00,182.0,5400.0,16,22,41315.0
17,0,NaN,bmw,gas,std,four,sedan,rwd,front,110.0,...,209,mpfi,3.62,3.39,8.00,182.0,5400.0,15,20,36880.0
18,2,121.0,chevrolet,gas,std,two,hatchback,fwd,front,88.4,...,61,2bbl,2.91,3.03,9.50,48.0,5100.0,47,53,5151.0
19,1,98.0,chevrolet,gas,std,two,hatchback,fwd,front,94.5,...,90,2bbl,3.03,3.11,9.60,70.0,5400.0,38,43,6295.0
20,0,81.0,chevrolet,gas,std,four,sedan,fwd,front,94.5,...,90,2bbl,3.03,3.11,9.60,70.0,5400.0,38,43,6575.0
21,1,118.0,dodge,gas,std,two,hatchback,fwd,front,93.7,...,90,2bbl,2.97,3.23,9.41,68.0,5500.0,37,41,5572.0
22,1,118.0,dodge,gas,std,two,hatchback,fwd,front,93.7,...,90,2bbl,2.97,3.23,9.40,68.0,5500.0,31,38,6377.0
23,1,118.0,dodge,gas,turbo,two,hatchback,fwd,front,93.7,...,98,mpfi,3.03,3.39,7.60,102.0,5500.0,24,30,7957.0
24,1,148.0,dodge,gas,std,four,hatchback,fwd,front,93.7,...,90,2bbl,2.97,3.23,9.40,68.0,5500.0,31,38,6229.0
25,1,148.0,dodge,gas,std,four,sedan,fwd,front,93.7,...,90,2bbl,2.97,3.23,9.40,68.0,5500.0,31,38,6692.0
26,1,148.0,dodge,gas,std,four,sedan,fwd,front,93.7,...,90,2bbl,2.97,3.23,9.40,68.0,5500.0,31,38,7609.0
27,1,148.0,dodge,gas,turbo,NaN,sedan,fwd,front,93.7,...,98,mpfi,3.03,3.39,7.60,102.0,5500.0,24,30,8558.0
28,-1,110.0,dodge,gas,std,four,wagon,fwd,front,103.3,...,122,2bbl,3.34,3.46,8.50,88.0,5000.0,24,30,8921.0
29,3,145.0,dodge,gas,turbo,two,hatchback,fwd,front,95.9,...,156,mfi,3.60,3.90,7.00,145.0,5000.0,19,24,12964.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,-1,65.0,toyota,gas,std,four,hatchback,fwd,front,102.4,...,122,mpfi,3.31,3.54,8.70,92.0,4200.0,27,32,9988.0
176,-1,65.0,toyota,gas,std,four,sedan,fwd,front,102.4,...,122,mpfi,3.31,3.54,8.70,92.0,4200.0,27,32,10898.0
177,-1,65.0,toyota,gas,std,four,hatchback,fwd,front,102.4,...,122,mpfi,3.31,3.54,8.70,92.0,4200.0,27,32,11248.0
178,3,197.0,toyota,gas,std,two,hatchback,rwd,front,102.9,...,171,mpfi,3.27,3.35,9.30,161.0,5200.0,20,24,16558.0
179,3,197.0,toyota,gas,std,two,hatchback,rwd,front,102.9,...,171,mpfi,3.27,3.35,9.30,161.0,5200.0,19,24,15998.0
180,-1,90.0,toyota,gas,std,four,sedan,rwd,front,104.5,...,171,mpfi,3.27,3.35,9.20,156.0,5200.0,20,24,15690.0
181,-1,NaN,toyota,gas,std,four,wagon,rwd,front,104.5,...,161,mpfi,3.27,3.35,9.20,156.0,5200.0,19,24,15750.0
182,2,122.0,volkswagen,diesel,std,two,sedan,fwd,front,97.3,...,97,idi,3.01,3.40,23.00,52.0,4800.0,37,46,7775.0
183,2,122.0,volkswagen,gas,std,two,sedan,fwd,front,97.3,...,109,mpfi,3.19,3.40,9.00,85.0,5250.0,27,34,7975.0
184,2,94.0,volkswagen,diesel,std,four,sedan,fwd,front,97.3,...,97,idi,3.01,3.40,23.00,52.0,4800.0,37,46,7995.0
185,2,94.0,volkswagen,gas,std,four,sedan,fwd,front,97.3,...,109,mpfi,3.19,3.40,9.00,85.0,5250.0,27,34,8195.0
186,2,94.0,volkswagen,gas,std,four,sedan,fwd,front,97.3,...,109,mpfi,3.19,3.40,9.00,85.0,5250.0,27,34,8495.0
187,2,94.0,volkswagen,diesel,turbo,four,sedan,fwd,front,97.3,...,97,idi,3.01,3.40,23.00,68.0,4500.0,37,42,9495.0
188,2,94.0,volkswagen,gas,std,four,sedan,fwd,front,97.3,...,109,mpfi,3.19,3.40,10.00,100.0,5500.0,26,32,9995.0
189,3,NaN,volkswagen,gas,std,two,convertible,fwd,front,94.5,...,109,mpfi,3.19,3.40,8.50,90.0,5500.0,24,29,11595.0
190,3,256.0,volkswagen,gas,std,two,hatchback,fwd,front,94.5,...,109,mpfi,3.19,3.40,8.50,90.0,5500.0,24,29,9980.0
191,0,NaN,volkswagen,gas,std,four,sedan,fwd,front,100.4,...,136,mpfi,3.19,3.40,8.50,110.0,5500.0,19,24,13295.0
192,0,NaN,volkswagen,diesel,turbo,four,sedan,fwd,front,100.4,...,97,idi,3.01,3.40,23.00,68.0,4500.0,33,38,13845.0
193,0,NaN,volkswagen,gas,std,four,wagon,fwd,front,100.4,...,109,mpfi,3.19,3.40,9.00,88.0,5500.0,25,31,12290.0
194,-2,103.0,volvo,gas,std,four,sedan,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.50,114.0,5400.0,23,28,12940.0
195,-1,74.0,volvo,gas,std,four,wagon,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.50,114.0,5400.0,23,28,13415.0
196,-2,103.0,volvo,gas,std,four,sedan,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.50,114.0,5400.0,24,28,15985.0
197,-1,74.0,volvo,gas,std,four,wagon,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.50,114.0,5400.0,24,28,16515.0
198,-2,103.0,volvo,gas,turbo,four,sedan,rwd,front,104.3,...,130,mpfi,3.62,3.15,7.50,162.0,5100.0,17,22,18420.0
199,-1,74.0,volvo,gas,turbo,four,wagon,rwd,front,104.3,...,130,mpfi,3.62,3.15,7.50,162.0,5100.0,17,22,18950.0
200,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.50,114.0,5400.0,23,28,16845.0
201,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.70,160.0,5300.0,19,25,19045.0
202,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.80,134.0,5500.0,18,23,21485.0
203,-1,95.0,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.00,106.0,4800.0,26,27,22470.0
204,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.50,114.0,5400.0,19,25,22625.0

In [57]:
auto.dtypes

symboling              int64
normalized_losses    float64
make                  object
fuel_type             object
aspiration            object
num_doors             object
body_style            object
drive_wheels          object
engine_location       object
wheel_base           float64
length               float64
width                float64
height               float64
curb_weight            int64
engine_type           object
num_cylinders         object
engine_size            int64
fuel_system           object
bore                 float64
stroke               float64
compression_ratio    float64
horsepower           float64
peak_rpm             float64
city_mpg               int64
highway_mpg            int64
price                float64
dtype: object

In [59]:
objCol=auto.select_dtypes(include=['object'])
objCol

,make,fuel_type,aspiration,num_doors,body_style,drive_wheels,engine_location,engine_type,num_cylinders,fuel_system
0,alfa-romero,gas,std,two,convertible,rwd,front,dohc,four,mpfi
1,alfa-romero,gas,std,two,convertible,rwd,front,dohc,four,mpfi
2,alfa-romero,gas,std,two,hatchback,rwd,front,ohcv,six,mpfi
3,audi,gas,std,four,sedan,fwd,front,ohc,four,mpfi
4,audi,gas,std,four,sedan,4wd,front,ohc,five,mpfi
5,audi,gas,std,two,sedan,fwd,front,ohc,five,mpfi
6,audi,gas,std,four,sedan,fwd,front,ohc,five,mpfi
7,audi,gas,std,four,wagon,fwd,front,ohc,five,mpfi
8,audi,gas,turbo,four,sedan,fwd,front,ohc,five,mpfi
9,audi,gas,turbo,two,hatchback,4wd,front,ohc,five,mpfi
10,bmw,gas,std,two,sedan,rwd,front,ohc,four,mpfi
11,bmw,gas,std,four,sedan,rwd,front,ohc,four,mpfi
12,bmw,gas,std,two,sedan,rwd,front,ohc,six,mpfi
13,bmw,gas,std,four,sedan,rwd,front,ohc,six,mpfi
14,bmw,gas,std,four,sedan,rwd,front,ohc,six,mpfi
15,bmw,gas,std,four,sedan,rwd,front,ohc,six,mpfi
16,bmw,gas,std,two,sedan,rwd,front,ohc,six,mpfi
17,bmw,gas,std,four,sedan,rwd,front,ohc,six,mpfi
18,chevrolet,gas,std,two,hatchback,fwd,front,l,three,2bbl
19,chevrolet,gas,std,two,hatchback,fwd,front,ohc,four,2bbl
20,chevrolet,gas,std,four,sedan,fwd,front,ohc,four,2bbl
21,dodge,gas,std,two,hatchback,fwd,front,ohc,four,2bbl
22,dodge,gas,std,two,hatchback,fwd,front,ohc,four,2bbl
23,dodge,gas,turbo,two,hatchback,fwd,front,ohc,four,mpfi
24,dodge,gas,std,four,hatchback,fwd,front,ohc,four,2bbl
25,dodge,gas,std,four,sedan,fwd,front,ohc,four,2bbl
26,dodge,gas,std,four,sedan,fwd,front,ohc,four,2bbl
27,dodge,gas,turbo,NaN,sedan,fwd,front,ohc,four,mpfi
28,dodge,gas,std,four,wagon,fwd,front,ohc,four,2bbl
29,dodge,gas,turbo,two,hatchback,fwd,front,ohc,four,mfi
...,...,...,...,...,...,...,...,...,...,...
175,toyota,gas,std,four,hatchback,fwd,front,ohc,four,mpfi
176,toyota,gas,std,four,sedan,fwd,front,ohc,four,mpfi
177,toyota,gas,std,four,hatchback,fwd,front,ohc,four,mpfi
178,toyota,gas,std,two,hatchback,rwd,front,dohc,six,mpfi
179,toyota,gas,std,two,hatchback,rwd,front,dohc,six,mpfi
180,toyota,gas,std,four,sedan,rwd,front,dohc,six,mpfi
181,toyota,gas,std,four,wagon,rwd,front,dohc,six,mpfi
182,volkswagen,diesel,std,two,sedan,fwd,front,ohc,four,idi
183,volkswagen,gas,std,two,sedan,fwd,front,ohc,four,mpfi
184,volkswagen,diesel,std,four,sedan,fwd,front,ohc,four,idi
185,volkswagen,gas,std,four,sedan,fwd,front,ohc,four,mpfi
186,volkswagen,gas,std,four,sedan,fwd,front,ohc,four,mpfi
187,volkswagen,diesel,turbo,four,sedan,fwd,front,ohc,four,idi
188,volkswagen,gas,std,four,sedan,fwd,front,ohc,four,mpfi
189,volkswagen,gas,std,two,convertible,fwd,front,ohc,four,mpfi
190,volkswagen,gas,std,two,hatchback,fwd,front,ohc,four,mpfi
191,volkswagen,gas,std,four,sedan,fwd,front,ohc,five,mpfi
192,volkswagen,diesel,turbo,four,sedan,fwd,front,ohc,four,idi
193,volkswagen,gas,std,four,wagon,fwd,front,ohc,four,mpfi
194,volvo,gas,std,four,sedan,rwd,front,ohc,four,mpfi
195,volvo,gas,std,four,wagon,rwd,front,ohc,four,mpfi
196,volvo,gas,std,four,sedan,rwd,front,ohc,four,mpfi
197,volvo,gas,std,four,wagon,rwd,front,ohc,four,mpfi
198,volvo,gas,turbo,four,sedan,rwd,front,ohc,four,mpfi
199,volvo,gas,turbo,four,wagon,rwd,front,ohc,four,mpfi
200,volvo,gas,std,four,sedan,rwd,front,ohc,four,mpfi
201,volvo,gas,turbo,four,sedan,rwd,front,ohc,four,mpfi
202,volvo,gas,std,four,sedan,rwd,front,ohcv,six,mpfi
203,volvo,diesel,turbo,four,sedan,rwd,front,ohc,six,idi
204,volvo,gas,turbo,four,sedan,rwd,front,ohc,four,mpfi

In [60]:
objCol['num_doors'].value_counts()

four    114
two      89
Name: num_doors, dtype: int64

In [63]:
objCol=objCol.fillna({'num_doors':'four'})
objCol

,make,fuel_type,aspiration,num_doors,body_style,drive_wheels,engine_location,engine_type,num_cylinders,fuel_system
0,alfa-romero,gas,std,two,convertible,rwd,front,dohc,four,mpfi
1,alfa-romero,gas,std,two,convertible,rwd,front,dohc,four,mpfi
2,alfa-romero,gas,std,two,hatchback,rwd,front,ohcv,six,mpfi
3,audi,gas,std,four,sedan,fwd,front,ohc,four,mpfi
4,audi,gas,std,four,sedan,4wd,front,ohc,five,mpfi
5,audi,gas,std,two,sedan,fwd,front,ohc,five,mpfi
6,audi,gas,std,four,sedan,fwd,front,ohc,five,mpfi
7,audi,gas,std,four,wagon,fwd,front,ohc,five,mpfi
8,audi,gas,turbo,four,sedan,fwd,front,ohc,five,mpfi
9,audi,gas,turbo,two,hatchback,4wd,front,ohc,five,mpfi
10,bmw,gas,std,two,sedan,rwd,front,ohc,four,mpfi
11,bmw,gas,std,four,sedan,rwd,front,ohc,four,mpfi
12,bmw,gas,std,two,sedan,rwd,front,ohc,six,mpfi
13,bmw,gas,std,four,sedan,rwd,front,ohc,six,mpfi
14,bmw,gas,std,four,sedan,rwd,front,ohc,six,mpfi
15,bmw,gas,std,four,sedan,rwd,front,ohc,six,mpfi
16,bmw,gas,std,two,sedan,rwd,front,ohc,six,mpfi
17,bmw,gas,std,four,sedan,rwd,front,ohc,six,mpfi
18,chevrolet,gas,std,two,hatchback,fwd,front,l,three,2bbl
19,chevrolet,gas,std,two,hatchback,fwd,front,ohc,four,2bbl
20,chevrolet,gas,std,four,sedan,fwd,front,ohc,four,2bbl
21,dodge,gas,std,two,hatchback,fwd,front,ohc,four,2bbl
22,dodge,gas,std,two,hatchback,fwd,front,ohc,four,2bbl
23,dodge,gas,turbo,two,hatchback,fwd,front,ohc,four,mpfi
24,dodge,gas,std,four,hatchback,fwd,front,ohc,four,2bbl
25,dodge,gas,std,four,sedan,fwd,front,ohc,four,2bbl
26,dodge,gas,std,four,sedan,fwd,front,ohc,four,2bbl
27,dodge,gas,turbo,four,sedan,fwd,front,ohc,four,mpfi
28,dodge,gas,std,four,wagon,fwd,front,ohc,four,2bbl
29,dodge,gas,turbo,two,hatchback,fwd,front,ohc,four,mfi
...,...,...,...,...,...,...,...,...,...,...
175,toyota,gas,std,four,hatchback,fwd,front,ohc,four,mpfi
176,toyota,gas,std,four,sedan,fwd,front,ohc,four,mpfi
177,toyota,gas,std,four,hatchback,fwd,front,ohc,four,mpfi
178,toyota,gas,std,two,hatchback,rwd,front,dohc,six,mpfi
179,toyota,gas,std,two,hatchback,rwd,front,dohc,six,mpfi
180,toyota,gas,std,four,sedan,rwd,front,dohc,six,mpfi
181,toyota,gas,std,four,wagon,rwd,front,dohc,six,mpfi
182,volkswagen,diesel,std,two,sedan,fwd,front,ohc,four,idi
183,volkswagen,gas,std,two,sedan,fwd,front,ohc,four,mpfi
184,volkswagen,diesel,std,four,sedan,fwd,front,ohc,four,idi
185,volkswagen,gas,std,four,sedan,fwd,front,ohc,four,mpfi
186,volkswagen,gas,std,four,sedan,fwd,front,ohc,four,mpfi
187,volkswagen,diesel,turbo,four,sedan,fwd,front,ohc,four,idi
188,volkswagen,gas,std,four,sedan,fwd,front,ohc,four,mpfi
189,volkswagen,gas,std,two,convertible,fwd,front,ohc,four,mpfi
190,volkswagen,gas,std,two,hatchback,fwd,front,ohc,four,mpfi
191,volkswagen,gas,std,four,sedan,fwd,front,ohc,five,mpfi
192,volkswagen,diesel,turbo,four,sedan,fwd,front,ohc,four,idi
193,volkswagen,gas,std,four,wagon,fwd,front,ohc,four,mpfi
194,volvo,gas,std,four,sedan,rwd,front,ohc,four,mpfi
195,volvo,gas,std,four,wagon,rwd,front,ohc,four,mpfi
196,volvo,gas,std,four,sedan,rwd,front,ohc,four,mpfi
197,volvo,gas,std,four,wagon,rwd,front,ohc,four,mpfi
198,volvo,gas,turbo,four,sedan,rwd,front,ohc,four,mpfi
199,volvo,gas,turbo,four,wagon,rwd,front,ohc,four,mpfi
200,volvo,gas,std,four,sedan,rwd,front,ohc,four,mpfi
201,volvo,gas,turbo,four,sedan,rwd,front,ohc,four,mpfi
202,volvo,gas,std,four,sedan,rwd,front,ohcv,six,mpfi
203,volvo,diesel,turbo,four,sedan,rwd,front,ohc,six,idi
204,volvo,gas,turbo,four,sedan,rwd,front,ohc,four,mpfi

In [65]:
pd.get_dummies(objCol,columns=['body_style','drive_wheels'],prefix=['body','drive']).head()

,make,fuel_type,aspiration,num_doors,engine_location,engine_type,num_cylinders,fuel_system,body_convertible,body_hardtop,body_hatchback,body_sedan,body_wagon,drive_4wd,drive_fwd,drive_rwd
0,alfa-romero,gas,std,two,front,dohc,four,mpfi,1,0,0,0,0,0,0,1
1,alfa-romero,gas,std,two,front,dohc,four,mpfi,1,0,0,0,0,0,0,1
2,alfa-romero,gas,std,two,front,ohcv,six,mpfi,0,0,1,0,0,0,0,1
3,audi,gas,std,four,front,ohc,four,mpfi,0,0,0,1,0,0,1,0
4,audi,gas,std,four,front,ohc,five,mpfi,0,0,0,1,0,1,0,0

###### Label Binarizer

In [67]:
from sklearn.preprocessing import LabelBinarizer
lb_style=LabelBinarizer()
lb_values=lb_style.fit_transform(objCol['engine_location'])

###### converting string values to integer values

In [69]:
objCol['num_doors'].value_counts()

four    116
two      89
Name: num_doors, dtype: int64

In [70]:
objCol['num_cylinders'].value_counts()

four      159
six        24
five       11
eight       5
two         4
twelve      1
three       1
Name: num_cylinders, dtype: int64

In [92]:
cleanup_strings={"num_cylinders":{"four":4,"two":2,'six':6,'five':5,'eight':8,'twelve':12,'three':3,np.nan:4}}
cleanup_strings

{'num_cylinders': {'four': 4,
  'two': 2,
  'six': 6,
  'five': 5,
  'eight': 8,
  'twelve': 12,
  'three': 3,
  nan: 4}}

In [85]:
objCol.replace(cleanup_strings,inplace=True)

In [86]:
objCol['num_doors'].unique()

array([2, 4], dtype=int64)

In [87]:
objCol['num_cylinders'].unique()

array([ 4,  6,  5,  3, 12,  2,  8], dtype=int64)

In [88]:
objCol[:3]

,make,fuel_type,aspiration,num_doors,body_style,drive_wheels,engine_location,engine_type,num_cylinders,fuel_system
0,alfa-romero,gas,std,2,convertible,rwd,front,dohc,4,mpfi
1,alfa-romero,gas,std,2,convertible,rwd,front,dohc,4,mpfi
2,alfa-romero,gas,std,2,hatchback,rwd,front,ohcv,6,mpfi

In [89]:
objCol.dtypes

make               object
fuel_type          object
aspiration         object
num_doors           int64
body_style         object
drive_wheels       object
engine_location    object
engine_type        object
num_cylinders       int64
fuel_system        object
dtype: object

In [90]:
objCol[objCol.isnull().any(axis=1)]

Empty DataFrame
Columns: [make, fuel_type, aspiration, num_doors, body_style, drive_wheels, engine_location, engine_type, num_cylinders, fuel_system]
Index: []

###### Label Encoder

In [93]:
objCol['make'].unique()

array(['alfa-romero', 'audi', 'bmw', 'chevrolet', 'dodge', 'honda',
       'isuzu', 'jaguar', 'mazda', 'mercedes-benz', 'mercury',
       'mitsubishi', 'nissan', 'peugot', 'plymouth', 'porsche', 'renault',
       'saab', 'subaru', 'toyota', 'volkswagen', 'volvo'], dtype=object)

In [104]:
from sklearn.preprocessing import LabelEncoder
#lb_make=LabelEncoder()

In [109]:
lb_make=LabelEncoder()
objCol['makeCode']=lb_make.fit_transform(objCol['make'])
objCol[['make','makeCode']].head()

          make  makeCode
0  alfa-romero         0
1  alfa-romero         0
2  alfa-romero         0
3         audi         1
4         audi         1

###### Custom Binary Encoding

In [99]:
objCol['engine_type'].value_counts()

ohc      148
ohcf      15
ohcv      13
dohc      12
l         12
rotor      4
dohcv      1
Name: engine_type, dtype: int64

In [110]:
objCol['OHC_Code']=np.where(objCol['engine_type'].str.contains('ohc'),1,0)
objCol.tail()

,make,fuel_type,aspiration,num_doors,body_style,drive_wheels,engine_location,engine_type,num_cylinders,fuel_system,OHC_Code,makeCode
200,volvo,gas,std,4,sedan,rwd,front,ohc,4,mpfi,1,21
201,volvo,gas,turbo,4,sedan,rwd,front,ohc,4,mpfi,1,21
202,volvo,gas,std,4,sedan,rwd,front,ohcv,6,mpfi,1,21
203,volvo,diesel,turbo,4,sedan,rwd,front,ohc,6,idi,1,21
204,volvo,gas,turbo,4,sedan,rwd,front,ohc,4,mpfi,1,21